"use client"
import React, { createContext, useContext, useReducer, useEffect, type Dispatch } from 'react'
import type { Message, Conversation, ActiveNav, ActiveView, WorkspaceFolder } from './types'
import { fetchMemories, fetchJournals, fetchSelfLearningSkills, fetchEnterpriseEvolution } from './api'

/**
 * 带重试的数据拉取（解决 mount 初始化时序：ensureAuthToken 可能尚未就绪）
 * - 首次失败或返回空数组 → 等 1s 重试 1 次
 * - 最终仍失败 → 打印 console.error 并返回空数组（不阻塞 UI）
 * - 仅供 AppProvider 内部使用；导出用于单元测试
 */
export async function fetchWithRetry<T>(
  label: string,
  fetcher: () => Promise<T[]>,
  retries = 2,
  delayMs = 1000,
): Promise<T[]> {
  const attempt = async (n: number): Promise<T[]> => {
    try {
      const result = await fetcher()
      if (result.length > 0) return result
      if (n < retries) {
        await new Promise(r => setTimeout(r, delayMs))
        return attempt(n + 1)
      }
      return []
    } catch (err) {
      console.error(`[store] ${label} 拉取失败 (第${n}次):`, err)
      if (n < retries) {
        await new Promise(r => setTimeout(r, delayMs))
        return attempt(n + 1)
      }
      return []
    }
  }
  return attempt(1)
}

export interface TaskSummary {
  id: string; time: string; title: string
  operations: string[]; findings: string[]; recommendations: string[]
  editing?: boolean
}
export interface OutputFile { id: string; name: string; type: string; createdAt: string; editing?: boolean }
export interface MemoryItem { id: string; category: string; content: string; createdAt: string; editing?: boolean }
export interface DiaryEntry { id: string; date: string; title: string; summary: string; editing?: boolean }
export interface SelfLearningSkill { id: string; name: string; description: string; autoGenerated: boolean; generatedAt: string; size: number }
export interface EnterpriseEvolutionEntry { timestamp: string; enterprise: string; knowledge: string[]; sessionId: string }

export interface AppState {
  activeNav: ActiveNav | ActiveView
  rightPanelOpen: boolean
  conversations: Conversation[]
  activeConversationId: string | null
  messages: Message[]
  sending: boolean
  /** 当前 SSE 进度提示（如"正在调用 check_permit_status…"） */
  progress: { step?: number; name?: string; text?: string } | null
  taskSummaries: TaskSummary[]
  outputFiles: OutputFile[]
  memories: MemoryItem[]
  diaryEntries: DiaryEntry[]
  selfLearningSkills: SelfLearningSkill[]
  enterpriseEvolution: EnterpriseEvolutionEntry[]
  /** 工作空间：用户选择的文件夹列表 */
  workspaceFolders: WorkspaceFolder[]
  /** 工作空间：当前会话绑定的工作空间 ID */
  activeWorkspaceId: string | null
  /** 跨模块预填对话输入（如知识库"询问AI"），chat-input 消费后置空 */
  prefillInput: string | null
  /** 协同审阅：当前审阅的文档ID */
  reviewDocId: string | null
  /** 协同审阅：AI 审阅结果 */
  reviewIssues: ReviewIssue[]
  /** 文档浏览器：当前打开的文档 */
  browserDoc: BrowserDoc | null
  /** 闭环：配额耗尽时的升级提示 */
  upgradePrompt: {
    message: string
    upgradeUrl: string
    reportsUsed: number
    reportsQuota: number
  } | null
}

export interface ReviewIssue {
  id: string
  type: 'error' | 'warning' | 'success' | 'info'
  label: string
  detail: string
  location?: string
}

export interface BrowserDoc {
  id: string
  title: string
  content: string
  type: 'md' | 'pdf' | 'docx' | 'pptx' | 'other'
  url?: string
  source: string
}

const STORAGE_KEY = 'ecopilot_state'

// ── 存储上限常量 ─────────────────────────────────
const MAX_CONVERSATIONS = 50
const MAX_MESSAGES_PER_CONVERSATION = 200
const MAX_TOOL_CALLS_PER_MESSAGE = 20
const MAX_TOOL_ARG_LENGTH = 2000
const MAX_TOOL_RESULT_LENGTH = 5000
const LS_WARN_THRESHOLD = 3 * 1024 * 1024 // 3MB

function loadState(): Partial<AppState> {
  if (typeof window === 'undefined') return {}
  try {
    const raw = localStorage.getItem(STORAGE_KEY)
    if (raw) {
      const size = new Blob([raw]).size
      if (size > LS_WARN_THRESHOLD) {
        console.warn(`[store] localStorage 使用量 ${(size / 1024 / 1024).toFixed(1)}MB，接近 5MB 上限`)
      }
      return JSON.parse(raw)
    }
  } catch (e) { console.error("[store] Failed to read state:", e) }
  return {}
}

function saveState(state: AppState) {
  if (typeof window === 'undefined') return
  try {
    const toSave = {
      conversations: state.conversations.map(c => ({ ...c, messages: c.messages || [] })),
      activeConversationId: state.activeConversationId,
      activeWorkspaceId: state.activeWorkspaceId,
      taskSummaries: state.taskSummaries,
      outputFiles: state.outputFiles,
      memories: state.memories,
      diaryEntries: state.diaryEntries,
    }
    const raw = JSON.stringify(toSave)
    const size = new Blob([raw]).size
    if (size > LS_WARN_THRESHOLD) {
      console.warn(`[store] localStorage 使用量 ${(size / 1024 / 1024).toFixed(1)}MB，接近 5MB 上限`)
    }
    // 超过 4.5MB 时拒绝写入（保留 0.5MB 余量）
    if (size > 4.5 * 1024 * 1024) {
      console.error('[store] localStorage 写入被阻止：超出 4.5MB 安全阈值')
      return
    }
    localStorage.setItem(STORAGE_KEY, raw)
  } catch (e) { console.error("[store] Failed to save state:", e) }
}

/** 裁剪会话列表：超限时移除最旧的非活动会话 */
function pruneConversations(convs: Conversation[], activeId: string | null): Conversation[] {
  if (convs.length <= MAX_CONVERSATIONS) return convs
  const active = convs.find(c => c.id === activeId)
  // 按更新时间降序排列，保留活动的，移除最旧的
  const sorted = [...convs].sort((a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime())
  const kept = sorted.slice(0, MAX_CONVERSATIONS)
  // 确保活动会话始终保留
  if (active && !kept.find(c => c.id === active.id)) {
    kept[kept.length - 1] = active
  }
  return kept
}

/** 裁剪消息列表：超限时移除最旧的消息 */
function pruneMessages(msgs: Message[]): Message[] {
  if (msgs.length <= MAX_MESSAGES_PER_CONVERSATION) return msgs
  // 保留系统消息和最新的消息
  return msgs.slice(-MAX_MESSAGES_PER_CONVERSATION)
}

/** 裁剪工具调用：限制数量和参数大小 */
function pruneToolCalls(toolCalls?: { name: string; args?: string; result?: string }[]): typeof toolCalls {
  if (!toolCalls || toolCalls.length === 0) return toolCalls
  return toolCalls.slice(-MAX_TOOL_CALLS_PER_MESSAGE).map(tc => ({
    ...tc,
    args: tc.args && tc.args.length > MAX_TOOL_ARG_LENGTH ? tc.args.slice(0, MAX_TOOL_ARG_LENGTH) + '…' : tc.args,
    result: tc.result && tc.result.length > MAX_TOOL_RESULT_LENGTH ? tc.result.slice(0, MAX_TOOL_RESULT_LENGTH) + '…' : tc.result,
  }))
}

// 注意：initialState 不依赖 localStorage（避免 SSR/客户端不一致导致 hydration 不匹配）
// 已保存的状态在 AppProvider mount 后通过 HYDRATE action 恢复
const initialState: AppState = {
  activeNav: 'chat',
  rightPanelOpen: false,
  conversations: [],
  activeConversationId: null,
  messages: [],
  sending: false,
  progress: null,
  taskSummaries: [],
  outputFiles: [],
  memories: [],
  diaryEntries: [],
  selfLearningSkills: [],
  enterpriseEvolution: [],
  workspaceFolders: [],
  activeWorkspaceId: null,
  prefillInput: null,
  reviewDocId: null,
  reviewIssues: [],
  browserDoc: null,
  upgradePrompt: null,
}

export type AppAction =
  | { type:'SET_NAV'; nav:ActiveNav|ActiveView }
  | { type:'TOGGLE_RIGHT_PANEL' }
  | { type:'ADD_MESSAGE'; message:Message }
  | { type:'REMOVE_LAST_MESSAGE' }
  | { type:'UPDATE_LAST_MESSAGE'; content:string }
  | { type:'SET_SENDING'; sending:boolean }
  | { type:'SET_PROGRESS'; progress:{ step?:number; name?:string; text?:string } | null }
  | { type:'ADD_TOOL_CALL'; toolCall:{ name:string; args?:string } }
  | { type:'UPDATE_TOOL_RESULT'; name:string; result:string }
  | { type:'CLEAR_TOOL_CALLS' }
  | { type:'SET_LAST_MESSAGE_ERROR'; error:string }
  | { type:'SET_CONVERSATION_ACTIVE'; id:string }
  | { type:'NEW_CONVERSATION' }
  | { type:'SET_CONVERSATION_TITLE'; id:string; title:string }
  | { type:'DELETE_CONVERSATION'; id:string }
  | { type:'ADD_TASK_SUMMARY'; summary:Omit<TaskSummary,'id'|'editing'> }
  | { type:'ADD_OUTPUT_FILE'; file:Omit<OutputFile,'id'|'editing'> }
  | { type:'ADD_MEMORY'; memory:Omit<MemoryItem,'id'|'editing'> }
  | { type:'ADD_DIARY_ENTRY'; entry:Omit<DiaryEntry,'id'|'editing'> }
  | { type:'EDIT_TASK_SUMMARY'; id:string; data:Partial<TaskSummary> }
  | { type:'DELETE_TASK_SUMMARY'; id:string }
  | { type:'DELETE_MEMORY'; id:string }
  | { type:'DELETE_DIARY'; id:string }
  | { type:'UPDATE_MEMORY'; id:string; data:Partial<MemoryItem> }
  | { type:'UPDATE_DIARY'; id:string; data:Partial<DiaryEntry> }
  | { type:'SET_PREFILL_INPUT'; text:string|null }
  | { type:'HYDRATE'; payload: Partial<AppState> }
  | { type:'SET_REVIEW_DOC'; id:string|null }
  | { type:'SET_REVIEW_ISSUES'; issues:ReviewIssue[] }
  | { type:'OPEN_BROWSER_DOC'; doc:BrowserDoc }
  | { type:'CLOSE_BROWSER_DOC' }
  | { type:'SET_UPGRADE_PROMPT'; prompt: AppState['upgradePrompt'] }
  | { type:'CLEAR_UPGRADE_PROMPT' }
  | { type:'ADD_WORKSPACE'; folder: WorkspaceFolder }
  | { type:'REMOVE_WORKSPACE'; id: string }
  | { type:'SET_WORKSPACE_ENTRIES'; id: string; entries: WorkspaceFolder['entries'] }
  | { type:'SET_ACTIVE_WORKSPACE'; id: string | null }

function uid() { return `${Date.now()}-${Math.random().toString(36).slice(2,6)}` }

/** 当前时间 "HH:MM" 格式 */
function nowTime() {
  return new Date().toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit' })
}

/** 从消息列表生成会话标题（取首条用户消息前 20 字） */
export function titleFromMessages(msgs: Message[]): string {
  const firstUser = msgs.find(m => m.role === 'user')
  if (firstUser) {
    const t = firstUser.content.replace(/\[图片\]/g, '').trim()
    return t ? t.slice(0, 20) : '新对话'
  }
  return '新对话'
}

/** 同步 conversations 中活动会话的 messages / lastMessage / time */
function syncActiveConv(state: AppState, msgs: Message[]): Partial<AppState> {
  const activeId = state.activeConversationId
  if (!activeId) return { messages: msgs }
  const lastMsg = msgs[msgs.length - 1]
  return {
    messages: msgs,
    conversations: state.conversations.map(c =>
      c.id === activeId
        ? {
            ...c,
            messages: msgs,
            lastMessage: lastMsg ? lastMsg.content.replace(/\n/g, ' ').slice(0, 50) : c.lastMessage,
            time: nowTime(),
          }
        : c
    ),
  }
}

export function reducer(state:AppState, action:AppAction):AppState {
  switch (action.type) {
    case 'SET_NAV': return { ...state, activeNav:action.nav }
    case 'TOGGLE_RIGHT_PANEL': return { ...state, rightPanelOpen:!state.rightPanelOpen }
    case 'SET_PROGRESS': return { ...state, progress: action.progress }

    case 'ADD_MESSAGE': {
      // 如果没有活动会话，自动创建一个
      if (!state.activeConversationId) {
        const newId = uid()
        const firstMsg = action.message
        const title = firstMsg.role === 'user' ? titleFromMessages([firstMsg]) : '新对话'
        const newConv: Conversation = {
          id: newId,
          title,
          lastMessage: firstMsg.content.replace(/\n/g, ' ').slice(0, 50),
          time: nowTime(),
          timestamp: new Date().toISOString(),
          unread: false,
          active: true,
          messages: [firstMsg],
          workspaceId: state.activeWorkspaceId || undefined,
        }
        return {
          ...state,
          messages: [firstMsg],
          conversations: pruneConversations([newConv, ...state.conversations.map(c => ({ ...c, active: false }))], newId),
          activeConversationId: newId,
        }
      }
      // 已有活动会话：追加消息并同步（裁剪消息数）
      const msgs = pruneMessages([...state.messages, action.message])
      return { ...state, ...syncActiveConv(state, msgs) }
    }

    case 'UPDATE_LAST_MESSAGE': {
      const msgs = pruneMessages([...state.messages])
      const last = msgs[msgs.length - 1]
      if (last?.role === 'assistant') {
        msgs[msgs.length - 1] = { ...last, content: (last.content + action.content).slice(0, 50000) }
      }
      return { ...state, ...syncActiveConv(state, msgs) }
    }

    case 'REMOVE_LAST_MESSAGE': {
      const msgs = state.messages.slice(0, -1)
      return { ...state, ...syncActiveConv(state, msgs) }
    }

    case 'SET_LAST_MESSAGE_ERROR': {
      const msgs = state.messages.map((m, i) =>
        i === state.messages.length - 1 && m.role === 'assistant'
          ? { ...m, pending: false, error: action.error }
          : m
      )
      return { ...state, ...syncActiveConv(state, msgs) }
    }

    case 'ADD_TOOL_CALL': {
      const msgs = state.messages.map((m, i) => {
        if (i === state.messages.length - 1 && m.role === 'assistant') {
          const toolCalls = [...(m.toolCalls || []), { name: action.toolCall.name, args: action.toolCall.args }]
          return { ...m, toolCalls: pruneToolCalls(toolCalls) }
        }
        return m
      })
      return { ...state, ...syncActiveConv(state, msgs) }
    }

    case 'UPDATE_TOOL_RESULT': {
      const msgs = state.messages.map((m, i) => {
        if (i === state.messages.length - 1 && m.role === 'assistant' && m.toolCalls) {
          const toolCalls = m.toolCalls.map(tc =>
            tc.name === action.name && !tc.result
              ? { ...tc, result: action.result }
              : tc
          )
          return { ...m, toolCalls: pruneToolCalls(toolCalls) }
        }
        return m
      })
      return { ...state, ...syncActiveConv(state, msgs) }
    }

    case 'CLEAR_TOOL_CALLS': {
      const msgs = state.messages.map(m =>
        m.role === 'assistant' ? { ...m, toolCalls: undefined } : m
      )
      return { ...state, ...syncActiveConv(state, msgs) }
    }

    case 'SET_SENDING': {
      const msgs = state.sending && !action.sending
        ? state.messages.map((m, i) => i === state.messages.length - 1 && m.role === 'assistant' ? { ...m, pending: false } : m)
        : state.messages
      return {
        ...state,
        sending: action.sending,
        messages: msgs,
        progress: action.sending ? state.progress : null,
        ...syncActiveConv(state, msgs),
      }
    }

    case 'SET_CONVERSATION_ACTIVE': {
      // 保存当前对话到 conversations 列表中
      const updated = state.conversations.map(c =>
        c.id === state.activeConversationId
          ? { ...c, messages: state.messages }
          : c
      )
      // 加载目标对话的 messages
      const target = updated.find(c => c.id === action.id)
      return {
        ...state,
        activeNav: 'chat',
        conversations: updated.map(c => ({ ...c, active: c.id === action.id, unread: c.id === action.id ? false : c.unread })),
        activeConversationId: action.id,
        messages: target?.messages || [],
        progress: null,
        taskSummaries: [], outputFiles: [], memories: [], diaryEntries: [],
      }
    }

    case 'NEW_CONVERSATION': {
      // 保存当前对话（如果有）
      let updated = state.conversations
      if (state.activeConversationId && state.messages.length > 0) {
        updated = state.conversations.map(c =>
          c.id === state.activeConversationId
            ? { ...c, messages: state.messages }
            : c
        )
      }
      return {
        ...state,
        activeNav: 'chat',
        conversations: updated.map(c => ({ ...c, active: false })),
        messages: [],
        activeConversationId: null,
        rightPanelOpen: false,
        progress: null,
        taskSummaries: [], outputFiles: [], memories: [], diaryEntries: [],
      }
    }

    case 'SET_CONVERSATION_TITLE':
      return { ...state, conversations: state.conversations.map(c => c.id === action.id ? { ...c, title: action.title } : c) }

    case 'DELETE_CONVERSATION': {
      const filtered = state.conversations.filter(c => c.id !== action.id)
      const wasActive = state.activeConversationId === action.id
      return {
        ...state,
        conversations: filtered,
        activeConversationId: wasActive ? null : state.activeConversationId,
        messages: wasActive ? [] : state.messages,
        rightPanelOpen: wasActive ? false : state.rightPanelOpen,
        progress: wasActive ? null : state.progress,
        taskSummaries: wasActive ? [] : state.taskSummaries,
      }
    }

    case 'ADD_TASK_SUMMARY':
      return { ...state, taskSummaries:[{...action.summary,id:uid()},...state.taskSummaries].slice(0,20), rightPanelOpen:true }
    case 'ADD_OUTPUT_FILE':
      return { ...state, outputFiles:[{...action.file,id:uid()},...state.outputFiles].slice(0,50) }
    case 'ADD_MEMORY':
      return { ...state, memories:[{...action.memory,id:uid()},...state.memories].slice(0,100) }
    case 'ADD_DIARY_ENTRY':
      return { ...state, diaryEntries:[{...action.entry,id:uid()},...state.diaryEntries].slice(0,200) }
    case 'EDIT_TASK_SUMMARY':
      return { ...state, taskSummaries:state.taskSummaries.map(s=>s.id===action.id?{...s,...action.data}:s) }
    case 'DELETE_TASK_SUMMARY':
      return { ...state, taskSummaries:state.taskSummaries.filter(s=>s.id!==action.id) }
    case 'DELETE_MEMORY':
      return { ...state, memories:state.memories.filter(m=>m.id!==action.id) }
    case 'DELETE_DIARY':
      return { ...state, diaryEntries:state.diaryEntries.filter(d=>d.id!==action.id) }
    case 'UPDATE_MEMORY':
      return { ...state, memories:state.memories.map(m=>m.id===action.id?{...m,...action.data}:m) }
    case 'UPDATE_DIARY':
      return { ...state, diaryEntries:state.diaryEntries.map(d=>d.id===action.id?{...d,...action.data}:d) }
    case 'SET_PREFILL_INPUT':
      return { ...state, prefillInput: action.text }
    case 'SET_REVIEW_DOC':
      return { ...state, reviewDocId: action.id, reviewIssues: [] }
    case 'SET_REVIEW_ISSUES':
      return { ...state, reviewIssues: action.issues }
    case 'OPEN_BROWSER_DOC':
      return { ...state, browserDoc: action.doc, rightPanelOpen: true }
    case 'CLOSE_BROWSER_DOC':
      return { ...state, browserDoc: null, reviewIssues: [] }
    case 'SET_UPGRADE_PROMPT':
      return { ...state, upgradePrompt: action.prompt }
    case 'CLEAR_UPGRADE_PROMPT':
      return { ...state, upgradePrompt: null }
    case 'ADD_WORKSPACE':
      // 去重：相同路径不重复添加
      if (state.workspaceFolders.some(f => f.path === action.folder.path)) return state
      return { ...state, workspaceFolders: [...state.workspaceFolders, action.folder], activeWorkspaceId: action.folder.id }
    case 'REMOVE_WORKSPACE': {
      const cleared = state.activeWorkspaceId === action.id ? null : state.activeWorkspaceId
      return { ...state, workspaceFolders: state.workspaceFolders.filter(f => f.id !== action.id), activeWorkspaceId: cleared }
    }
    case 'SET_ACTIVE_WORKSPACE':
      return { ...state, activeWorkspaceId: action.id }
    case 'SET_WORKSPACE_ENTRIES':
      return {
        ...state,
        workspaceFolders: state.workspaceFolders.map(f =>
          f.id === action.id ? { ...f, entries: action.entries, loaded: true } : f
        ),
      }
    case 'HYDRATE': {
      // 从 localStorage 恢复持久化状态（mount 后调用，避免 hydration 不匹配）
      // 仅更新 payload 中显式传入的字段，不覆盖未传入的字段（避免并发 dispatch 相互覆盖）
      const p = action.payload
      const next = { ...state }
      if (p.conversations !== undefined) {
        next.conversations = pruneConversations(
          (p.conversations || []).map(c => ({ ...c, messages: pruneMessages(c.messages || []) })),
          p.activeConversationId || null
        )
      }
      if (p.activeConversationId !== undefined) next.activeConversationId = p.activeConversationId
      if (p.conversations !== undefined || p.activeConversationId !== undefined) {
        const activeId = p.activeConversationId ?? state.activeConversationId
        const activeConv = (p.conversations || state.conversations).find(c => c.id === activeId)
        next.messages = activeConv?.messages || []
      }
      if (p.taskSummaries !== undefined) next.taskSummaries = p.taskSummaries
      if (p.outputFiles !== undefined) next.outputFiles = p.outputFiles
      if (p.memories !== undefined) next.memories = p.memories
      if (p.diaryEntries !== undefined) next.diaryEntries = p.diaryEntries
      if (p.selfLearningSkills !== undefined) next.selfLearningSkills = p.selfLearningSkills
      if (p.enterpriseEvolution !== undefined) next.enterpriseEvolution = p.enterpriseEvolution
      if (p.workspaceFolders !== undefined) next.workspaceFolders = p.workspaceFolders
      if (p.activeWorkspaceId !== undefined) next.activeWorkspaceId = p.activeWorkspaceId
      if (p.browserDoc !== undefined) next.browserDoc = p.browserDoc
      if (p.reviewDocId !== undefined) next.reviewDocId = p.reviewDocId
      if (p.reviewIssues !== undefined) next.reviewIssues = p.reviewIssues
      return next
    }
    default: return state
  }
}

const AppContext = createContext<{state:AppState;dispatch:Dispatch<AppAction>}|null>(null)

export function AppProvider({children}:{children:React.ReactNode}) {
  const [state, dispatch] = useReducer(reducer, initialState)

  // mount 后从 localStorage 恢复持久化状态（避免 SSR/客户端不一致导致 hydration 不匹配）
  useEffect(() => {
    const saved = loadState()
    if (saved && Object.keys(saved).length > 0) {
      dispatch({ type: 'HYDRATE', payload: saved })
    }
  }, [])

  // mount 后从后端拉取合规记忆和工作日志（后端数据优先于 localStorage）
  useEffect(() => {
    fetchWithRetry("合规记忆", fetchMemories)
      .then(memories => {
        if (memories.length > 0) {
          dispatch({ type: 'HYDRATE', payload: { memories } })
        }
      })

    fetchWithRetry("工作日志", fetchJournals)
      .then(journals => {
        if (journals.length > 0) {
          dispatch({ type: 'HYDRATE', payload: { diaryEntries: journals } })
        }
      })

    fetchWithRetry("自学习技能", fetchSelfLearningSkills)
      .then(skills => {
        if (skills.length > 0) {
          dispatch({ type: 'HYDRATE', payload: { selfLearningSkills: skills } })
        }
      })

    fetchWithRetry("企业进化日志", fetchEnterpriseEvolution)
      .then(entries => {
        if (entries.length > 0) {
          dispatch({ type: 'HYDRATE', payload: { enterpriseEvolution: entries } })
        }
      })
  }, [])

  // 自动持久化
  useEffect(() => {
    const t = setTimeout(() => saveState(state), 500)
    return () => clearTimeout(t)
  }, [state.conversations, state.activeConversationId, state.taskSummaries, state.memories, state.diaryEntries, state.selfLearningSkills, state.enterpriseEvolution])

  return React.createElement(AppContext.Provider, { value: { state, dispatch } }, children)
}

export function useApp() {
  const ctx = useContext(AppContext)
  if (!ctx) throw new Error('useApp must be used within AppProvider')
  return ctx
}
